### ISSUE TITLE
Dead Project?

### ISSUE THREAD

**Issue by BigBallard** [EveHQ-Team/EveHQ-NG#14]
By the lack of activity I presume this will not come to fruition?

**Comment by Slivo-fr** [comment]
Hey,

I didn't have news from eshva in a long time.. I'd say he probably gave up

**Comment by Eshva** [comment]
Namaste!
I'm ready to transfer ownership on project to someone.

Dallas Phillips ***@***.***> 15 июня 2022 г. 5:22:46 AM написал:

**Comment by BigBallard** [comment]
Do we think this is still a project that could prove some help in the Eve community?

**Comment by BigBallard** [comment]
Either case I am willing to take on ownership to try and make something of this 👍🏽 Ill give it a year or two and see about getting some other developers involved after a while @Eshva

**Comment by Slivo-fr** [comment]
If you wish to take over the project and eshva is fine with that, we could talk about adding you to the EveHQ-Team group so you can work from this repository

**Comment by BigBallard** [comment]
Ya that would be cool! I would like an understanding to be made in that I will most likely not commit to the initial architecture choices that Eshva did and will change some things but with the end goal of a cross-platform desktop app still of course. If that is all fine then ya taking this project on would be a lot of fun.

**Comment by Eshva** [comment]
I gave to Dallas write permissions on the repository.
Welcome!

**Comment by Slivo-fr** [comment]
If you want some more informations about what was evehq and how it work let me know

**Comment by BigBallard** [comment]
thanks @Slivo-fr will do!
